from pathlib import Path

app = Path('public/app.js')
text = app.read_text()
old = '''    ${recommendation && winner ? `<article class="panel recommendation-hero"><div class="recommendation-main"><div><span class="recommendation-label">VENDOR SCOUT RECOMMENDS</span><h2>${escapeHtml(recommendation.supplierName)}</h2><p>${escapeHtml(recommendation.status === "provisional" ? "Provisional recommendation — some cost evidence remains incomplete." : "Best current evidence across economics, lead time, supplier quality, MOQ, sample terms, and completeness.")}</p></div><div class="recommendation-score"><strong>${Number.isFinite(recommendation.score) ? recommendation.score.toFixed(1) : "—"}</strong><span>decision score</span></div></div><div class="recommendation-metrics"><span>Negotiated unit<b>${money2(winner.unitPrice?.base)}</b><small>Current ${money2(currentMission.currentSupplier.unitPrice)}</small></span><span>${escapeHtml(cost.label)}<b>${escapeHtml(cost.value)}</b><small>${cost.complete ? "Comparable landed economics" : "Incomplete cost evidence"}</small></span><span>Projected savings<b>${money(savings)}</b><small>${Number.isFinite(savingsPercent) ? `${savingsPercent.toFixed(1)}% vs current` : "vs current supplier"}</small></span><span>Lead time<b>${days(winner.leadTimeDays)}</b><small>Current ${days(currentMission.currentSupplier.leadTimeDays)}</small></span><span>MOQ<b>${number(winner.moq)}</b><small>${number(currentMission.quantity)} units requested</small></span><span>Sample<b>${winner.sample?.available === true ? money2(samplePrice) : "—"}</b><small>Budget ${money2(currentMission.constraints.sampleBudget)}</small></span></div><div class="recommendation-evidence"><div><h3>Why this offer</h3>${reasons}</div>${risks}</div></article>` : ""}
    <div class="section-title decision-section-title"><div><p class="eyebrow">NORMALIZED QUOTE COMPARISON</p><h2>${displayQuotes.length ? `${displayQuotes.length} supplier offer${displayQuotes.length === 1 ? "" : "s"} · ${ranked.length} rankable` : "Waiting for comparison"}</h2></div><span class="local-badge">Deterministic scoring</span></div><div class="quote-grid">${quoteCards}</div>
    <div class="section-title decision-section-title"><div><p class="eyebrow">HUMAN COMMITMENT BOUNDARY</p><h2>One decision. Full evidence.</h2></div></div>${decisionState}`;
'''
new = '''    ${recommendation && winner ? `<article class="panel recommendation-hero"><div class="recommendation-main"><div><span class="recommendation-label">VENDOR SCOUT RECOMMENDS</span><h2>${escapeHtml(recommendation.supplierName)}</h2><p>${escapeHtml(recommendation.status === "provisional" ? "Provisional recommendation — some cost evidence remains incomplete." : "Best current evidence across economics, lead time, supplier quality, MOQ, sample terms, and completeness.")}</p></div><div class="recommendation-score"><strong>${Number.isFinite(recommendation.score) ? recommendation.score.toFixed(1) : "—"}</strong><span>decision score</span></div></div><div class="recommendation-metrics"><span>Negotiated unit<b>${money2(winner.unitPrice?.base)}</b><small>Current ${money2(currentMission.currentSupplier.unitPrice)}</small></span><span>${escapeHtml(cost.label)}<b>${escapeHtml(cost.value)}</b><small>${cost.complete ? "Comparable landed economics" : "Incomplete cost evidence"}</small></span><span>Projected savings<b>${money(savings)}</b><small>${Number.isFinite(savingsPercent) ? `${savingsPercent.toFixed(1)}% vs current` : "vs current supplier"}</small></span><span>Lead time<b>${days(winner.leadTimeDays)}</b><small>Current ${days(currentMission.currentSupplier.leadTimeDays)}</small></span><span>MOQ<b>${number(winner.moq)}</b><small>${number(currentMission.quantity)} units requested</small></span><span>Sample<b>${winner.sample?.available === true ? money2(samplePrice) : "—"}</b><small>Budget ${money2(currentMission.constraints.sampleBudget)}</small></span></div><div class="recommendation-evidence"><div><h3>Why this offer</h3>${reasons}</div>${risks}</div></article>` : ""}
    <div class="section-title decision-section-title commitment-title"><div><p class="eyebrow">HUMAN COMMITMENT BOUNDARY</p><h2>One decision. Full evidence.</h2></div></div>${decisionState}
    <div class="section-title decision-section-title"><div><p class="eyebrow">NORMALIZED QUOTE COMPARISON</p><h2>${displayQuotes.length ? `${displayQuotes.length} supplier offer${displayQuotes.length === 1 ? "" : "s"} · ${ranked.length} rankable` : "Waiting for comparison"}</h2></div><span class="local-badge">Deterministic scoring</span></div><div class="quote-grid">${quoteCards}</div>`;
'''
if old not in text: raise SystemExit('decision layout anchor not found')
app.write_text(text.replace(old, new, 1))

html = Path('public/index.html')
text = html.read_text()
text = text.replace('/procurement.css?v=vendor-scout-5', '/procurement.css?v=vendor-scout-6', 1)
text = text.replace('The approval packet is designed to show current versus proposed economics, lead time, MOQ, shipping, supplier risk, competing offers, sample terms, and the recommendation.', 'The live decision packet shows current versus negotiated economics, landed cost, lead time, MOQ, shipping, supplier risk, competing offers, sample terms, and the recommendation before any commitment.', 1)
text = text.replace('Open approval boundary', 'Open decision packet', 1)
text = text.replace('<footer><span>Future actions</span><b>Approve · Keep negotiating · Reject</b></footer>', '<footer><span>Human actions</span><b>Approve sample · Keep negotiating · Reject</b></footer>', 1)
text = text.replace('Vendor Scout already implements the persistent TrueForge session and ten-tool sourcing, outreach, and negotiation MCP boundary; a live external TrueForge runtime is the remaining configuration step.', 'Vendor Scout implements a persistent TrueForge session, a 12-tool procurement MCP boundary, sandbox-verified quote analysis, and a destructive sample-order tool designed to pause for TrueForge approval immediately before execution.', 1)
text = text.replace('Attach TrueForge to the existing discovery, qualification, outreach, and negotiation action boundary.', 'Attach TrueForge to the discovery, qualification, outreach, negotiation, comparison, and approved-action boundary.', 1)
text = text.replace('Pause at consequential actions and resume only after the human decides.', 'Create the business decision packet, then pause again at the destructive execution tool before the approved action runs.', 1)
text = text.replace('Discovery, qualification, RFQ outreach, and evidence-backed counter negotiation now run through one persistent sourcing mission.', 'The end-to-end controlled path now runs through discovery, qualification, RFQ outreach, negotiation, quote comparison, human approval, and an approval-gated sample action.', 1)
html.write_text(text)
